Create the tag crud
n00bia/MemoryBook pull request #1
Opened 2024-06-07 01:27 UTC by n00bia

:D

2024-06-07 16:21 UTC, marciojmo commented
> :D

Na mensagem do commit tu podes incluir uma visão geral do que foi feito. Ex:
Add tag repository and controller.

2024-06-10 21:26 UTC, marciojmo commented on Repository/TagRepository.cs
> +            TagModel wantedTag = _dbContext.Tags.FirstOrDefault(q => q.Id == tag.Id);
Notei que no DeleteById tu reusaste o GetById porém no UpdateById há repetição do código ` TagModel wantedTag = _dbContext.Tags.FirstOrDefault(q => q.Id == tag.Id);`. O UpdateById também está sem o async. Teve alguma razão específica para isso?

2024-06-10 21:26 UTC, marciojmo commented on Repository/TagRepository.cs
Eu particularmente prefiro deixar a lógica do "verificar se o registro existe" no controlador. No repositório costumo deixar os métodos com a função única de deletar / atualizar mesmo. Lembrando que a função do Repository é  "abstrair o acesso aos dados" e também separar esse acesso das regras de negócio.

Não sei se no .net core é assim, mas ficaria algo assim:
```
public async Task<void> DeleteById(int id)
{
           TagModel tag = _dbContext.TagModel.Find(id);
           _dbContext.TagModel.Remove(tag);
           await _dbContext.SaveChangesAsync();
}
```

```
public async Task<TagModel> Update(TagModel tag)
{
        _dbContext.Entry(tag).State = EntityState.Modified;
        await _dbContext.SaveChangesAsync();
}
```
O código ficaria mais conciso.

2024-06-10 21:26 UTC, marciojmo commented on Repository/TagRepository.cs
> +            TagModel wantedTag = _dbContext.Tags.FirstOrDefault(q => q.Id == tag.Id);
@n00bia

2024-06-10 21:26 UTC, marciojmo commented on Repository/TagRepository.cs
@n00bia

2024-06-18 19:03 UTC, marciojmo requested changes

2024-06-18 19:03 UTC, marciojmo commented on Repository/TagRepository.cs
> +            TagModel wantedTag = await GetById(tag.Id);
Essa chamada ainda é necessária?

2024-06-19 16:01 UTC, n00bia commented on Repository/TagRepository.cs
> +            TagModel wantedTag = await GetById(tag.Id);
Por que vc acha que não?

2024-07-10 18:19 UTC, marciojmo commented on Repository/TagRepository.cs
> +        public async Task<TagModel> Update(TagModel tag)
Aqui não está faltando algo como `_context.Tags.Update(tag);` ? Não tem nada indicando que vai atualizar a tag recebida.

2024-07-11 15:02 UTC, marciojmo approved these changes
Mandou bem! xD

2024-07-11 17:05 UTC, merged